" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Install and run vim-plug on first run
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" NERD tree will be loaded on the first invocation of NERDTreeToggle command
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

" autocompletion
Plug 'Valloric/YouCompleteMe', { 'do': 'python3 install.py --clang-completer'}
"Plug 'zxqfl/tabnine-vim', { 'do': './install.sh --clang-completer', 'for': ['c', 'cpp', 'python'] }

" fzf
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" useful plugins
Plug 'ntpeters/vim-better-whitespace'
Plug 'Lokaltog/vim-easymotion'
Plug 'tpope/vim-fugitive'
Plug 'itchyny/lightline.vim'
Plug 'maximbaz/lightline-ale'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'dense-analysis/ale'
Plug 'scrooloose/nerdcommenter'
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
Plug 'yuttie/comfortable-motion.vim'
Plug 'jiangmiao/auto-pairs'

" theme
Plug 'tomasr/molokai'
Plug 'morhetz/gruvbox'

" Initialize plugin system
call plug#end()

" disable backup files
set nobackup
set nowb
set noswapfile
set noerrorbells
set t_vb=

" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" set up clipboard, mouse and always scroll at center
set mouse=a
set ttymouse=xterm2
set so=999
set clipboard=unnamedplus
set wildmenu
if has('mac')
    set clipboard=unnamed
endif

" basic configuration
if has("gui_running")
"tell the term has 256 colors
  set t_Co=256
end
syntax on
set autoindent
set number
set title
set titlestring=%F\ -\ vim
set noshowmode
set laststatus=2
set showtabline=2
set background=dark

set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set visualbell                  "No sounds
set autoread

" theme
" colorscheme molokai
colorscheme gruvbox
" for gruvbox theme
let g:gruvbox_vert_split = 'bg1'
let g:gruvbox_sign_column = 'bg0'
hi Normal ctermbg=NONE
hi CursorLineNr ctermfg=white
hi SignColumn ctermbg=NONE

" python 80 chars limitation per line
autocmd filetype python setlocal colorcolumn=80

" encoding
set encoding=utf-8
set termencoding=utf-8
set fileencodings=ucs-bom,utf-8,sjis,big5,gbk,latin1

" file behaviour
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set backspace=indent,eol,start
set smarttab
set linebreak
set breakindent
set nostartofline

" search
set smartcase
set hlsearch
set incsearch

" panes
set splitbelow
set splitright

" custom binding
let mapleader = " "
nnoremap <Leader>h gT
nnoremap <Leader>l gt
" move tabe
map <Leader>ml :tabmove +1<CR>
map <Leader>mh :tabmove -1<CR>
map <Leader><space> :StripWhitespace<cr>

" easymotion
map <Leader> <Plug>(easymotion-prefix)

" enable highlighting and stripping whitespace on save by default
let g:better_whitespace_enabled = 1
let g:strip_whitespace_on_save = 1

" nertree
map <Leader>n :NERDTreeToggle<CR>
let NERDTreeShowHidden = 1

" disable pymode checking
let g:pymode_lint = 0

" ale
let g:ale_fix_on_save = 1
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

" Lightline
let g:lightline = {
    \ 'active': {
    \   'left': [['mode', 'paste'], ['readonly', 'filename', 'modified']],
    \   'right': [['lineinfo'], ['percent'], ['gitbranch', 'fileformat', 'fileencoding'],['linter_checking', 'linter_warnings', 'linter_errors', 'linter_ok']]
    \ },
    \ 'component_function': {
    \    'gitbranch': 'gitbranch#name'
    \ },
    \ 'component_expand': {
    \   'linter_warnings': 'LightlineLinterWarnings',
    \   'linter_errors': 'LightlineLinterErrors',
    \   'linter_ok': 'LightlineLinterOK'
    \ },
    \ 'component_type': {
    \   'readonly': 'error',
    \   'linter_warnings': 'warning',
    \   'linter_errors': 'error'
    \ },
    \ }
function! LightlineLinterWarnings() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '' : printf('%d ◆', all_non_errors)
endfunction
function! LightlineLinterErrors() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '' : printf('%d ✘', all_errors)
endfunction
function! LightlineLinterOK() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '✓ ' : ''
endfunction

" Update and show lightline but only if it's visible (e.g., not in Goyo)
function! s:MaybeUpdateLightline()
  if exists('#lightline')
    call lightline#update()
  end
endfunction

" Update the lightline scheme from the colorscheme. Hopefully.
function! s:UpdateLightlineColorScheme()
  let g:lightline.colorscheme = g:colors_name
  call lightline#init()
endfunction

augroup _lightline
  autocmd!
  autocmd User ALELint call s:MaybeUpdateLightline()
  autocmd ColorScheme * call s:UpdateLightlineColorScheme()
augroup END

" fzf
map <Leader>; :Files<cr>
